---
title: "Project Proposal"
date: "2025-11-06"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_float: true
---
```{r}
library(tidyverse)
```

### The group members (names and UNIs)
Disheng Jiang (dj2763), Yurou Liu (yl6109), Ruhui Shen (rs4788), Juan Tang (jt3649)

### The tentative project title

### The motivation for this project

### The intended final products

### The anticipated data sources

### The planned analyses / visualizations / coding challenges

### The planned timeline
```{r}
timeline = tibble(
  date = c(
    "11/7",
    "11/8–11/12",
    "11/12–11/16",
    "11/15–11/16",
    "11/16–11/19",
    "11/19–11/20",
    "11/21–11/26",
    "11/26–12/1",
    "12/2–12/3",
    "12/3–12/6"
  ),
  work = c(
    "Determine project topic, find data source, complete the proposal",
    "Zoom meeting: determine final datasets and how to analyze data",
    "Complete final source collection",
    "Zoom meeting: determine detailed division of work",
    "Clean and tidy data",
    "Zoom meeting: design website structure",
    "Plot graphs and analyze data",
    "Complete report with visualizations and interpretations",
    "Proofread report",
    "Final webpage improvement and screencast"
  )
)

timeline |>
  knitr::kable(
    caption = "Project Timeline",
    align = c("c", "l")
  )
```

