---
title: "Reference"
output: 
  html_document:
    code_folding: hide
    theme: flatly
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background literature

This page summarizes key articles that informed the design of our project on coffee consumption and health:


1. Asoudeh F, Bagheri A, Larijani B, Esmaillzadeh A. Coffee consumption and caffeine intake in relation to risk of fractures: a systematic review and dose-response meta-analysis of observational studies. *Crit Rev Food Sci Nutr.* 2023;63(28):9039–9051. [doi:10.1080/10408398.2022.2067114](https://doi.org/10.1080/10408398.2022.2067114)

2. Barrea L, Pugliese G, Frias-Toral E, El Ghoch M, Castellucci B, et al. Coffee consumption, health benefits and side effects: a narrative review and update for dietitians and nutritionists. *Crit Rev Food Sci Nutr.* 2023;63(9):1238–1261. [doi:10.1080/10408398.2021.1963207](https://doi.org/10.1080/10408398.2021.1963207)

3. Carter P, Yuan S, Kar S, Vithayathil M, Mason AM, et al. Coffee consumption and cancer risk: a Mendelian randomisation study. *Clin Nutr.* 2022;41(10):2113–2123. [doi:10.1016/j.clnu.2022.08.019](https://doi.org/10.1016/j.clnu.2022.08.019)

4. Herqutanto T, Rosemiarti T, Dewi DK, Soemarko DS, Syam AF, et al. Coffee consumption and alertness: a study among office workers in Jakarta. *Front Nutr.* 2024;11:1425707. [doi:10.3389/fnut.2024.1425707](https://doi.org/10.3389/fnut.2024.1425707)